# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
#
# Adapted from the skimage project (https://github.com/scikit-image/scikit-image)

environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python38
    - PYTHON: C:\Python38-x64
    - PYTHON: C:\Python39
    - PYTHON: C:\Python39-x64

matrix:
  fast_finish: true

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip build"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip --version"
  - "python -m build --version"
  - "python -m pip list"

  # Install the build and runtime dependencies of the project.
  - python -m build --sdist --wheel
  - ps: "ls dist"

  # Install the generated wheel package to test it
  - "python -m pip install --pre --no-index --find-links dist/ lap"

# Not a .NET project, we build lap in the install step instead
build: false

test_script:
  # Run unit tests with pytest
  - "python -m pip install pytest pytest-timeout"
  - "python -m pytest

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
