[project]
name = "lap"
description = "Linear Assignment Problem solver (LAPJV/LAPMOD)"
readme = "README.md"
#requires-python = ">=3.8"
keywords = ["lapjv", "lapmod", "linear assignment problem"]
authors = [{name = "Tomas Kazmar", email = "tomash.kazmar@seznam.cz"}]
version = "0.5dev"
license = {file = "LICENSE"}
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"Intended Audience :: Developers",
	"Programming Language :: C",
	"Programming Language :: Python",
	"Programming Language :: Python :: 2",
	"Programming Language :: Python :: 2.7",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX",
	"Operating System :: Unix",
	"Operating System :: MacOS",
]
dependencies = [
	"numpy",
]

[project.optional-dependencies]
dev = ["build", "wheel", "cython"]

[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#which-import-mode
addopts = [
    "--import-mode=importlib",
]
