# CircleCI docs:
# https://circleci.com/docs/2.1/configuration-reference
# https://circleci.com/developer/orbs/orb/circleci/python
# https://circleci.com/docs/2.0/executor-types/
# https://circleci.com/docs/2.0/configuration-reference/#jobs
# https://circleci.com/docs/2.0/configuration-reference/#workflows
#
version: 2.1

jobs:
  test:
    docker:
      - image: ubuntu:jammy
    steps:
      - run:
          name: Check setup
          command: |
            pwd
            ls
            whoami
            ls ~
            uname -a || true
            which python || true
            python --version || true
      - checkout
      # Not-working alternative below:
      #- run:
      #    name: Clone repo
      #    command: |
      #      apt-get update
      #      apt-get install -y git
      #      git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
      - run:
          name: Install tested Python versions
          command: bash -x ./tools/install_pythons.sh
      - run:
          name: Create a virtual environment
          command: |
            python3 -m venv ~/venv-tox
            source ~/venv-tox/bin/activate
            python -m pip -U pip setuptools
            python -m pip install tox tox-pyenv
      - run:
          name: Run tox
          command: python3 -m tox

workflows:
  testing:
    jobs:
      - test
