# CircleCI docs:
# https://circleci.com/docs/2.1/configuration-reference
# https://circleci.com/developer/orbs/orb/circleci/python
# https://circleci.com/docs/2.0/executor-types/
# https://circleci.com/docs/2.0/configuration-reference/#jobs
# https://circleci.com/docs/2.0/configuration-reference/#workflows
#
version: 2.1

jobs:
  test:
    docker:
      - image: ubuntu:jammy
    steps:
      - run:
          name: Clone repo
          command: |
            apt-get install -y git
            git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL"
      - run:
          name: Check setup
          command: |
            pwd
            ls
            whoami
            ls ~
            uname -a
            which python
            python --version
      - run:
          name: Install tested Python versions
          command: ./tools/install_pythons.sh
      - run:
          name: Install tox
          command: python -m pip install tox tox-pyenv
      - run:
          name: Run tox
          command: python -m tox

workflows:
  testing:
    jobs:
      - test
